[package]
name = "ysc-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitbuffer = "0.10.9"
joaat = "0.1.0"
rayon = "1.6.1"
rand = "0.8.5"
itertools = "0.10.5"